BUILD_MAX_JOBS=8

DOCKER_IMAGE_NAMESPACE ?= jetson-stacks
DOCKER_IMAGE_TAG ?= dev

DOCKER_BUILD_CMD := docker build --build-arg max_jobs=$(BUILD_MAX_JOBS)

BASE_DOCKER_IMAGE_NAME := base
BUILD_FROM_BASE_IMAGE := $(DOCKER_BUILD_CMD) --build-arg BASE_IMAGE=$(DOCKER_IMAGE_NAMESPACE)/$(BASE_DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
base:
	cd packages/base && \
	$(DOCKER_BUILD_CMD) -t $(DOCKER_IMAGE_NAMESPACE)/$(BASE_DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .

BASE_TEST_DOCKER_IMAGE_NAME := base-test
base-test: base
	cd packages/base-test && \
	$(BUILD_FROM_BASE_IMAGE) -t $(DOCKER_IMAGE_NAMESPACE)/$(BASE_TEST_DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .

LLM_BASE_DOCKER_IMAGE_NAME := llm-base
BUILD_FROM_LLM_BASE_IMAGE := $(DOCKER_BUILD_CMD) --build-arg BASE_IMAGE=$(DOCKER_IMAGE_NAMESPACE)/$(LLM_BASE_DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG)
llm-base: base
	cd packages/llm-base && \
	$(BUILD_FROM_BASE_IMAGE) -t $(DOCKER_IMAGE_NAMESPACE)/$(LLM_BASE_DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_TAG) .
